#!/bin/sh

CUR=`pwd`

echo "Updating sublime settings"
ln -sf $CUR/sublime/Preferences.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Preferences.sublime-settings
cp -f sublime/Russian-English.dic ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/Russian-English.dic
cp -f sublime/Russian-English.aff ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/Russian-English.aff

echo "Updating git config"
cp -f gitconfig ~/.gitconfig
git config --global --replace-all core.excludesfile ~/.gitconfig
cp -f gitignore ~/.gitignore

echo "Installing zshkit"
rm -Rf ~/.zshkit
cp -Rf zshkit ~/.zshkit
~/.zshkit/install

echo "Adding extra lines to ~/.zshrc"
cat zshrc_addons >> ~/.zshrc

echo "Updating submodules"
git submodule init
git submodule update
git submodule foreach git co master
git submodule foreach git pull

cd $CUR
echo "Install complete!"
