#!/bin/sh

CUR=`pwd`

echo "~/.gitconfig"
cp -f gitconfig ~/.gitconfig
git config --global --replace-all core.excludesfile ~/.gitconfig

echo "~/.gitignore"
cp -f gitignore ~/.gitignore

echo "Installing zshkit"
rm -Rf ~/.zshkit
cp -Rf zshkit ~/.zshkit
~/.zshkit/install

echo "Adding homedir extra lines to ~/.zshrc"
cat zshrc_addons >> ~/.zshrc
echo "Done"

echo "Updating submodules"
git submodule init
git submodule update
git submodule foreach git co master
git submodule foreach git pull

cd $CUR
echo "Done"
